-keepattributes *Annotation*
-keep class kotlinx.serialization.** { *; }
-keepclassmembers class dev.boardmydelulu.anupam.data.model.** { *; }
-dontwarn okhttp3.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
